version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: bharathkumarkathi225/mysql:v1
    container_name: mysql   # --name mysql
    volumes:
    - mysql:/var/lib/mysql  # -v mysql:/var/lib/mysql
  backend:
    image: bharathkumarkathi225/backend:v1
    container_name: backend          # for frontend, no need of volume,backend is just code
    command: sh -c "sleep 5 && node /opt/server/index.js"   # after mysql is created, backend should give time to mysql to be up and then it can connect to mysql
    depends_on:
    - mysql
  frontend:
    image: bharathkumarkathi225/frontend:v1
    container_name: frontend
    ports:       # for frontend, no need of volume,frontend is just code
    - 80:80
    depends_on:
    - backend